/**
 * AgentMarket — navbar אחיד (RTL, Supabase auth)
 * דורש טעינה אחרי <body> (בדרך כלל בסוף הדף).
 *
 * Supabase SQL (run once in SQL editor):
 * CREATE TABLE public.notifications (
 *   id bigint generated by default as identity primary key,
 *   user_id uuid not null,
 *   title text not null,
 *   message text not null,
 *   is_read boolean default false,
 *   created_at timestamptz default now()
 * );
 */
(function () {
  var SUPABASE_URL = "https://ugvmystwnfrglzaxpput.supabase.co";
  var SUPABASE_ANON_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndm15c3R3bmZyZ2x6YXhwcHV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDExODIsImV4cCI6MjA5MDYxNzE4Mn0.PtWBhJO3G5lQ3NQTfihHmVIIoK1AAaX9MTDyqP_YnSA";

  var STYLE_ID = "am-navbar-styles";
  var NAV_ID = "am-navbar";

  function injectStyles() {
    if (document.getElementById(STYLE_ID)) return;
    var style = document.createElement("style");
    style.id = STYLE_ID;
    style.textContent =
      "#" +
      NAV_ID +
      "{position:fixed;top:0;left:0;right:0;z-index:10001;background:#fff;border-bottom:1px solid #d8e2ee;box-shadow:0 2px 12px rgba(24,95,165,.08);}" +
      "#" +
      NAV_ID +
      " .am-navbar-inner{max-width:1200px;margin:0 auto;padding:10px 16px;display:flex;flex-direction:row;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;font-family:'Segoe UI',Arial,sans-serif;}" +
      "#" +
      NAV_ID +
      " .am-navbar-start{display:flex;align-items:center;gap:14px;flex-wrap:wrap;}" +
      "#" +
      NAV_ID +
      " .am-navbar-logo{font-size:1.1rem;font-weight:700;color:#185FA5;text-decoration:none;white-space:nowrap;}" +
      "#" +
      NAV_ID +
      " .am-navbar-logo:hover{color:#11497f;}" +
      "#" +
      NAV_ID +
      " .am-navbar-links{display:flex;align-items:center;gap:8px;flex-wrap:wrap;}" +
      "#" +
      NAV_ID +
      " .am-navbar-links a{font-size:0.92rem;font-weight:600;color:#185FA5;text-decoration:none;padding:6px 10px;border-radius:8px;}" +
      "#" +
      NAV_ID +
      " .am-navbar-links a:hover{background:rgba(24,95,165,.1);}" +
      "#" +
      NAV_ID +
      " .am-navbar-end{display:flex;align-items:center;gap:8px;flex-wrap:wrap;}" +
      "#" +
      NAV_ID +
      " .am-notif-wrap{position:relative;}" +
      "#" +
      NAV_ID +
      " .am-bell{border:1px solid #185FA5;background:#fff;color:#185FA5;border-radius:10px;padding:7px 10px;cursor:pointer;font-size:14px;line-height:1;}" +
      "#" +
      NAV_ID +
      " .am-bell-count{position:absolute;top:-6px;left:-6px;min-width:18px;height:18px;padding:0 5px;border-radius:999px;background:#185FA5;color:#fff;font-size:11px;display:none;align-items:center;justify-content:center;}" +
      "#" +
      NAV_ID +
      " .am-notif-menu{position:absolute;top:36px;left:0;width:300px;max-height:360px;overflow:auto;background:#fff;border:1px solid #d8e2ee;border-radius:12px;box-shadow:0 12px 30px rgba(20,62,103,.15);display:none;z-index:10010;}" +
      "#" +
      NAV_ID +
      " .am-notif-item{padding:10px 12px;border-bottom:1px solid #edf2f8;cursor:pointer;}" +
      "#" +
      NAV_ID +
      " .am-notif-item:last-child{border-bottom:none;}" +
      "#" +
      NAV_ID +
      " .am-notif-title{font-size:12px;font-weight:700;color:#185FA5;margin-bottom:3px;}" +
      "#" +
      NAV_ID +
      " .am-notif-message{font-size:12px;color:#1b1f24;line-height:1.35;}" +
      "#" +
      NAV_ID +
      " .am-notif-empty{padding:12px;color:#5f6b7a;font-size:12px;}" +
      "#" +
      NAV_ID +
      " .am-nav-user{display:none;align-items:center;gap:10px;flex-wrap:wrap;}" +
      "#" +
      NAV_ID +
      " .am-nav-guest{display:flex;align-items:center;gap:8px;flex-wrap:wrap;}" +
      "#" +
      NAV_ID +
      " .am-nav-hello{font-size:0.9rem;font-weight:600;color:#1b1f24;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}" +
      "#" +
      NAV_ID +
      " .am-btn-primary{font-size:0.88rem;font-weight:700;padding:8px 14px;border-radius:10px;border:none;background:#185FA5;color:#fff;text-decoration:none;cursor:pointer;font-family:inherit;}" +
      "#" +
      NAV_ID +
      " .am-btn-primary:hover{background:#11497f;}" +
      "#" +
      NAV_ID +
      " .am-btn-outline{font-size:0.88rem;font-weight:600;padding:8px 14px;border-radius:10px;border:1px solid #185FA5;background:#fff;color:#185FA5;text-decoration:none;cursor:pointer;font-family:inherit;}" +
      "#" +
      NAV_ID +
      " .am-btn-outline:hover{background:rgba(24,95,165,.08);}" +
      "body.am-navbar-pad{padding-top:56px !important;}";
    document.head.appendChild(style);
  }

  function injectNav() {
    if (document.getElementById(NAV_ID)) return;
    var nav = document.createElement("nav");
    nav.id = NAV_ID;
    nav.setAttribute("dir", "rtl");
    nav.setAttribute("lang", "he");
    nav.setAttribute("aria-label", "ניווט ראשי");
    nav.innerHTML =
      '<div class="am-navbar-inner">' +
      '<div class="am-navbar-start">' +
      '<a class="am-navbar-logo" href="dashboard.html">AgentMarket</a>' +
      '<div class="am-navbar-links">' +
      '<a href="dashboard.html">מרקטפלייס</a>' +
      '<a href="add-agent.html">הוסף סוכן</a>' +
      '<a href="profile.html">Profile</a>' +
      '<a href="manage-requests.html">Requests</a>' +
      '<a href="orders.html">My Orders</a>' +
      "</div>" +
      "</div>" +
      '<div class="am-navbar-end">' +
      '<div class="am-notif-wrap">' +
      '<button type="button" id="am-bell" class="am-bell" aria-label="Notifications">🔔</button>' +
      '<span id="am-bell-count" class="am-bell-count">0</span>' +
      '<div id="am-notif-menu" class="am-notif-menu"></div>' +
      "</div>" +
      '<div id="am-nav-user" class="am-nav-user">' +
      '<span id="am-nav-hello" class="am-nav-hello"></span>' +
      '<button type="button" id="am-nav-logout" class="am-btn-outline">התנתק</button>' +
      "</div>" +
      '<div id="am-nav-guest" class="am-nav-guest">' +
      '<a class="am-btn-outline" href="login.html">התחבר</a>' +
      '<a class="am-btn-primary" href="index.html">הירשם</a>' +
      "</div>" +
      "</div>" +
      "</div>";
    document.body.insertBefore(nav, document.body.firstChild);
    document.body.classList.add("am-navbar-pad");
  }

  function displayName(user) {
    if (!user) return "";
    return (
      (user.user_metadata && user.user_metadata.full_name) ||
      (user.user_metadata && user.user_metadata.name) ||
      user.email ||
      "משתמש"
    );
  }

  function ensureSupabase(callback) {
    if (window.supabase) {
      callback();
      return;
    }
    var s = document.createElement("script");
    s.src = "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";
    s.onload = function () {
      callback();
    };
    s.onerror = function () {
      console.error("[navbar] failed to load Supabase");
    };
    document.head.appendChild(s);
  }

  function updateAuthUI(client) {
    var guest = document.getElementById("am-nav-guest");
    var userBox = document.getElementById("am-nav-user");
    var hello = document.getElementById("am-nav-hello");
    if (!guest || !userBox || !hello) return;

    client.auth.getUser().then(function (res) {
      var u = res.data && res.data.user;
      if (u && !res.error) {
        guest.style.display = "none";
        userBox.style.display = "flex";
        hello.textContent = "Hello " + displayName(u);
      } else {
        userBox.style.display = "none";
        guest.style.display = "flex";
      }
    });
  }

  function bindLogout(client) {
    var btn = document.getElementById("am-nav-logout");
    if (!btn || btn.dataset.amBound) return;
    btn.dataset.amBound = "1";
    btn.addEventListener("click", function () {
      client.auth.signOut().then(function () {
        window.location.href = "login.html";
      });
    });
  }

  function renderNotifications(items) {
    var menu = document.getElementById("am-notif-menu");
    var countEl = document.getElementById("am-bell-count");
    if (!menu || !countEl) return;
    var unreadCount = items.filter(function (n) { return !n.is_read; }).length;
    countEl.textContent = String(unreadCount);
    countEl.style.display = unreadCount > 0 ? "inline-flex" : "none";
    if (!items.length) {
      menu.innerHTML = '<div class="am-notif-empty">No notifications</div>';
      return;
    }
    menu.innerHTML = items.map(function (n) {
      return (
        '<div class="am-notif-item" data-id="' + n.id + '">' +
        '<div class="am-notif-title">' + (n.title || "Notification") + "</div>" +
        '<div class="am-notif-message">' + (n.message || "") + "</div>" +
        "</div>"
      );
    }).join("");
  }

  function bindNotificationUI(client) {
    var bell = document.getElementById("am-bell");
    var menu = document.getElementById("am-notif-menu");
    if (!bell || !menu || bell.dataset.bound) return;
    bell.dataset.bound = "1";

    bell.addEventListener("click", function (event) {
      event.stopPropagation();
      menu.style.display = menu.style.display === "block" ? "none" : "block";
    });
    document.addEventListener("click", function () {
      menu.style.display = "none";
    });
    menu.addEventListener("click", async function (event) {
      var item = event.target.closest(".am-notif-item");
      if (!item) return;
      var id = item.getAttribute("data-id");
      await client.from("notifications").update({ is_read: true }).eq("id", id);
      await loadNotifications(client);
    });
  }

  async function loadNotifications(client) {
    var res = await client.auth.getUser();
    var user = res.data && res.data.user;
    if (!user) {
      renderNotifications([]);
      return;
    }
    var q = await client
      .from("notifications")
      .select("*")
      .eq("user_id", user.id)
      .order("created_at", { ascending: false })
      .limit(15);
    if (q.error) {
      renderNotifications([]);
      return;
    }
    renderNotifications(q.data || []);
  }

  function init() {
    injectStyles();
    injectNav();
    ensureSupabase(function () {
      if (!window.AgentMarketSupabase) {
        window.AgentMarketSupabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
      }
      var supabaseClient = window.AgentMarketSupabase;
      bindLogout(supabaseClient);
      updateAuthUI(supabaseClient);
      bindNotificationUI(supabaseClient);
      loadNotifications(supabaseClient);
      supabaseClient.auth.onAuthStateChange(function () {
        updateAuthUI(supabaseClient);
        loadNotifications(supabaseClient);
      });
    });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
